services:
  - type: web
    name: praxis
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
